<?php

use DoSomething\GatewayTests\Helpers\JsonResponse;

class ForwardsTransactionIdsTest extends TestCase
{
    /** @test */
    public function it_should_set_new_id()
    {
        $client = new ForwardsTransactionIdsClient([new JsonResponse()]);

        $response = $client->get('/hello');

        // We should see a `X-Request-Id` on the request.
        $this->assertArrayHasKey('X-Request-ID', $client->getLastRequest()->getHeaders());
    }

    /** @test */
    public function it_should_increment_existing_ids()
    {
        // Let's pretend that we are handling a request with an `X-Request-Id`
        // header attached to it (generated by another internal service).
        $requestId = '754546b2-a67f-47d1-9eda-203c8f989601';
        $this->withRequestHeader('X-Request-ID', $requestId);

        $logger = Mockery::spy();
        $client = new ForwardsTransactionIdsClient([new JsonResponse()]);
        $client->setLogger($logger);

        $response = $client->get('/hello');

        // We should see the existing `X-Request-Id` on the request.
        $this->assertEquals([$requestId], $client->getLastRequest()->getHeader('X-Request-ID'));
    }
}
