name: CI

on: [push]

jobs:
  test:
    runs-on: php:7.2-cli
    steps:
      - uses: actions/checkout@master
      - name: Checkout
        uses: actions/checkout@master
      - name: Install SQLite
        run: |
          sudo apt-get update
          sudo apt-get install sqlite3
          docker-php-ext-enable sqlite3
      - name: Install dependencies
        run: composer install
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

