name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install SQLite
        run: |
          sudo apt-get update
          sudo apt-get install sqlite3
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.2
          extension-csv: sqlite3
      - name: Install dependencies
        run: composer install
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

